direction: right
vars: {
  d2-config: {
    layout-engine: elk
  }
}

120VAC -> 12VDC
120VAC -> 5VDC

5VDC -> Arduino
5VDC -> BinSwitch -> Arduino.Pin5
Arduino.Pin11 -> IR LED
5VDC -> IR Photosensor -> Arduino.Pin6
5VDC -> UpperTankFloat -> Arduino.Pin7
5VDC -> LowerTankFloat -> Arduino.Pin8
5VDC -> PowerSwitch -> Arduino.Pin3


120VAC -> CompressorRelay -> Compressor
120VAC -> MotorRelay -> Ammeter -> Motor

Ammeter -> Arduino.Pin12

Arduino.Pin1 -> CompressorRelay
Arduino.Pin2 -> MotorRelay

Arduino.Pin10 -> UVLightMosfet-> UVLight
12VDC -> UVLightMosfet

12VDC -> BinLightSwitch -> BinLight

Arduino.Pin9 -> FanMosfet -> Fan
12VDC -> FanMosfet

Arduino.Pin4 -> PumpMosfet -> Pump
12VDC -> PumpMosfet
