vars: {
  d2-config: {
    theme-id: 200
  }
}
direction: right
title: Flow of water &\npiping diagram {
  shape: text
  near: top-center
  style: {
    font-size: 55
  }
}

* {
  style: {
    font-size: 30
  }
}

external tank -> front tank
front tank -> pump
pump -> internal tank
internal tank -> T junction
T junction -> drain hose
T junction -> ice maker

ice maker -> ice melting -> front tank {
  style: {
    stroke-dash: 3
  }
}
